spring:
  jpa:
    hibernate:
      ddl-auto: create  # 프로덕션 환경에서는 자동 테이블 생성을 비활성화
    properties:
      hibernate:
        format_sql: true  # SQL 로그 포맷을 비활성화하여 성능 향상
    defer-datasource-initialization: true  # 데이터베이스 연결 초기화 지연

  datasource:
    hikari:
      maximum-pool-size: 30         # 최대 커넥션 수
      minimum-idle: 5               # 최소 커넥션 수
      idle-timeout: 600000          # 커넥션 유휴 시 제거까지 대기 시간
      max-lifetime: 1800000         # 커넥션 최대 생존 시간
      connection-timeout: 30000     # 커넥션 기다리는 최대 시간

  data:
    redis:
      host: 43.203.172.46

  # 프로덕션 환경에서는 SQL 스크립트 초기화 비활성화
  sql:
    init:
      mode: always # 항상 초기화하지 않도록 설정

  elasticsearch:
    uris: "43.203.172.46:9200"  # Elasticsearch 서버 URI
    username: elastic

  main:
    allow-bean-definition-overriding: true

logging.level:
  org.hibernate.SQL: warn  # Hibernate SQL 로그는 경고 수준으로 설정
  com.zaxxer.hikari.HikariConfig: OFF  # HikariConfig 로그를 끔
  com.zaxxer.hikari: OFF  # Hikari 로그를 끔

server:
  port: 80  # 서버 포트를 80으로 변경

oauth:
  kakao:
    redirect-uri: https://www.mybooknest.site/oauth/kakao/callback  # 운영 도메인으로 변경
  google:
    redirect-uri: https://www.mybooknest.site/oauth/google/callback  # 운영 도메인으로 변경
  naver:
    redirect-uri: https://www.mybooknest.site/oauth/naver/callback # 운영 도메인으로 변경

