spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false

  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000 

  data:
    redis:
      host: ${server.address}

  sql:
    init:
      mode: never

  elasticsearch:
    uris: "${server.address}:9200"
    username: elastic

  main:
    allow-bean-definition-overriding: true

logging.level:
  org.hibernate.SQL: warn
  com.zaxxer.hikari.HikariConfig: OFF
  com.zaxxer.hikari: OFF

server:
  port: 80

oauth:
  kakao:
    redirect-uri: https://www.mybooknest.site/oauth/kakao/callback
  google:
    redirect-uri: https://www.mybooknest.site/oauth/google/callback
  naver:
    redirect-uri: https://www.mybooknest.site/oauth/naver/callback

